AllCops:
  NewCops: enable
  Exclude:
    - 'config/**/*'
    - 'bin/bundle'
    - 'db/**/*'
    - 'spec/*.rb'

Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: true
  Exclude:
  - 'spec/**/*'